# Copyright 2025 The ChapaUY Authors
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of go.mod
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(go): "
    open-pull-requests-limit: 5
  - package-ecosystem: "gomod"
    directory: "/.dagger" # Location of go.mod for dagger
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(dagger): "
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/web" # Location of package.json
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(js): "
    open-pull-requests-limit: 5
